server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sagar
    url: jdbc:mysql://localhost:3306/inventory
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: inventory-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




