server:
  port: 8082



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product
        - id: inventory_route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: discovery_server
          uri: http://localhost:8761
          filters:
            - SetPath=/
          predicates:
            - Path=/eureka/web
        - id: discovery_server_static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-boot-relem
  zipkin:
    base-url: http://localhost:9411
management.tracing.sampling:
  probability: 1.0



  application:
    name: api-gateway

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE


