server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sagar
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  order-service: "http://localhost:8082"
