server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sagar
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
        show-details: always



services:
  order-service: "http://inventory-service"

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 100
        minimumNumberOfCalls: 10
        # timeout
        timeout-duration: 3s
