spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
      name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0