spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
      name: product-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    locator:
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management.tracing.sampling.probability: 1.0

server:
  port: 0