#server:
#  port: 8082
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: sagar
#    url: jdbc:mysql://localhost:3306/inventory
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
spring:
  application:
    name: discovery-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    locator:
      discovery:
        enabled: true

management.tracing.sampling.probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761